# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy JAR app to Azure Web App - actions-spring-app

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    services: # Define los servicios que se ejecutarán en paralelo con el flujo de trabajo
      mysql:
        image: mysql:latest # Versión de la imagen de MySQL a utilizar
        env:
          MYSQL_ROOT_PASSWORD: 1234
          MYSQL_DATABASE: testbanco
          MYSQL_USER: juan
          MYSQL_PASSWORD: 1234
        ports:
          - 3306:3306
    
    steps:
      - uses: actions/checkout@v4

      - name: Set up Java version
        uses: actions/setup-java@v1
        with:
          java-version: '17'

      - uses: actions/checkout@v3 # Acción para clonar el repositorio en el runner
      - name: Set up JDK 17 # Configura el JDK 17 en el runner
        uses: actions/setup-java@v3 # Acción para configurar el JDK en el runner
        with:   # Parámetros de la acción
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: Install dockerize # Instala dockerize en el runner
        run: |
          wget https://github.com/jwilder/dockerize/releases/download/v0.6.1/dockerize-linux-amd64-v0.6.1.tar.gz
          tar -xzvf dockerize-linux-amd64-v0.6.1.tar.gz
          sudo mv dockerize /usr/local/bin
      - name: Wait for MySQL to be ready # Espera a que MySQL esté listo
        run: |
          sudo apt-get update -y
          sudo apt-get install -y mysql-client
          dockerize -wait tcp://localhost:3306 -timeout 1m
          
      - name: Build with Maven
        run: mvn clean install

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v3
        with:
          name: java-app
          path: '${{ github.workspace }}/target/*.jar'

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write #This is required for requesting the JWT
  
    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: java-app
      
      - name: Login to Azure
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_CED9D32B04FB4706998BCB31ABECE74F }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_A850A06AAD7841959B586FEE42EAEED5 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_A718FA5ADFF445E6BC888AAD6D963CFA }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'actions-spring-app'
          slot-name: 'Production'
          package: '*.jar'
