# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# Más GitHub Actions para Azure: https://github.com/Azure/actions

name: Build and deploy JAR app to Azure Web App - spring-app-server

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Java version
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt' # Distribucion compatible con Oracle JDK

      - name: Build with Maven
        run: mvn clean install

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v3
        with:
          name: java-app
          path: '${{ github.workspace }}/target/*.jar'

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write # Esto es necesario para solicitar el JWT
  
    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: java-app
      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_16C92900893642FDA055944F5F2D0CF9 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_58625003171B4200AFCE878683D768B0 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_D0D3E2887CF24656BF716CEB35AD58E8 }}
          
      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'spring-app-server'
          slot-name: 'Production'
          package: '*.jar'



          
