name: Java CI with Maven and MySQL

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:latest
        env:
          MYSQL_ROOT_PASSWORD: 1234
          MYSQL_DATABASE: testbanco
          MYSQL_USER: juan
          MYSQL_PASSWORD: 1234
        ports:
          - 3306:3306

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Install dockerize
      run: |
        wget https://github.com/jwilder/dockerize/releases/download/v0.6.1/dockerize-linux-amd64-v0.6.1.tar.gz
        tar -xzvf dockerize-linux-amd64-v0.6.1.tar.gz
        sudo mv dockerize /usr/local/bin
    - name: Wait for MySQL to be ready
      run: dockerize -wait tcp://localhost:3306 -timeout 1m
    - name: Build with Maven
      run: mvn -B package --file pom.xml
